local_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency:  1.0
  publish_frequency: 2.0
  transform_tolerance: 0.3  

  static_map: true
  rolling_window: false
  width: 10
  height: 10
  resolution: 0.05
 